name : api
on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: docker compose up -d
      - run: npm run test 